@baseUrl = Azure AI Search のエンドポイント URL
@index-name = インデックス名
@api-key = Azure AI Search のクエリ キー

POST {{baseUrl}}/indexes/{{index-name}}/docs/search?api-version=2024-07-01
Content-Type: application/json
api-key: {{api-key}}

{
  "count": true,
  "select": "title, chunk",
  "vectorQueries": [
    {
      "kind": "text",
      "text": "Azure OpenAI の保護",
      "fields": "text_vector",
      "k": 3,
      "exhaustive": true
    }
  ]
}